{
  config,
  lib,
  ...
}: let
  cfg = config.homelab.services.alloy;

  dropEnabled = cfg.loki.systemd.dropEnable;
  rules = cfg.loki.systemd.dropRules;

  # Escape for HCL string context: \ -> \\ and " -> \"
  hclEscape = s:
    lib.replaceStrings ["\\" "\""] ["\\\\" "\\\""] s;

  renderRule = r: ''
    // ${r.name}
    stage.match {
      selector = "{unit=\"${hclEscape r.unit}\"}"

      stage.drop {
        expression = "${hclEscape r.expression}"
      }
    }
  '';

  renderedRules =
    if dropEnabled
    then lib.concatMapStrings renderRule rules
    else "";

  dropText = ''
    // -------------------------
    // Auto-generated by NixOS
    // Drop pipeline (noise filtering only)
    // -------------------------
    loki.process "systemd_drop" {
      ${renderedRules}
      forward_to = [loki.process.systemd.receiver]
    }
  '';
in {
  config = lib.mkIf cfg.enable {
    environment.etc."alloy/loki-systemd-drop.alloy".text = dropText;
  };
}
