keys:
  - &accesscontrolsystem
    age1rx9mw350ymp2xwua05peyg0f8s354ad8lxl9kkzwkg7pmwnh2q3qvg3z8e
  - &watchfulsystem
    age1sh9wz07py8qysc3dvf228r85pfafaraf0a23244stpxanmq68slq06cxx6
  - &nastest
    age1m24xcey4jcvyjncz4krmzwy9m6efqvr0jrzdjxfxg8fsalt83cqqpwnz3j
  - &murderbot
    age1s90xwvtqw9at892s8tyde9lp8vu3rs2lde7pwh7hayuc2sahmv6qmkwpff
  - &caretaker
    age1gqvw59226drpwn8942x55jcf5zca5gfupj9eppmeagfevx3pupzs78dfs6
  - &failsafeunit
    age14vkyvuykxaceu3hwmwf5uscs54prr507vvgejwjcmp4taq0klcsqzkdsuu
  - &oci-auth-server
    age18lt8cq0zcj468qsd7xzjj2mayl557sf4g8jy6mde429v926g0sjsmj3d53
  - &oci-vpn-server
    age1x3fnwasxkjjsr2c9ygrtu47yugwvvrt87vx86k9dn5z69v5csfpsk2n0j3
  - &pve-app-1
    age1vs8ffqtt3hfdtur82tv59z6kfwf27nk4e46nrkrj79jcmuxdsy2sag38sf
  - &pve-database
    age1m72xl459t3rws9y9m8ks2madx64f86dde33www6fqpnd6h4lec2skhlwxd
  - &pve-monitoring
    age1trh5rr42turkhzcxyxfv3ana72htqlevdglnsdyhn9e3atct7vpshyg87q
  - &pve-proxy
    age16fd6tkmtpqy9kg04s0amn37mdj2vp0p7fngalu3244kw589x9qvqfnw62q

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *accesscontrolsystem
          - *watchfulsystem
          - *nastest
          - *murderbot
          - *caretaker
          - *failsafeunit
          - *oci-auth-server
          - *oci-vpn-server
          - *pve-app-1
          - *pve-database
          - *pve-monitoring
          - *pve-proxy

  - path_regex: secrets/accesscontrolsystem-server\.yaml$
    key_groups:
      - age:
        - *accesscontrolsystem
        - *murderbot

  - path_regex: secrets/watchfulsystem-server\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *watchfulsystem

  - path_regex: secrets/oci-auth-server\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *oci-auth-server

  - path_regex: secrets/oci-vpn-server\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *oci-vpn-server

  - path_regex: secrets/caretaker\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *caretaker

  - path_regex: secrets/failsafeunit\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *failsafeunit

  - path_regex: secrets/pve-app-1\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *pve-app-1

  - path_regex: secrets/pve-database\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *pve-database

  - path_regex: secrets/pve-monitoring\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *pve-monitoring

stores:
  yaml:
    indent: 2
  json:
    indent: 2
