keys:
  - &murderbot
    age1s90xwvtqw9at892s8tyde9lp8vu3rs2lde7pwh7hayuc2sahmv6qmkwpff
  - &caretaker
    age1gqvw59226drpwn8942x55jcf5zca5gfupj9eppmeagfevx3pupzs78dfs6
  - &oci-proxy-server
    age12n44qwj28glz06dhzkzxgy7ff85y7yw0kcwn99zycclwm6qmsgnsapws5a
  - &oci-auth-server
    age18lt8cq0zcj468qsd7xzjj2mayl557sf4g8jy6mde429v926g0sjsmj3d53
  - &oci-vpn-server
    age1x3fnwasxkjjsr2c9ygrtu47yugwvvrt87vx86k9dn5z69v5csfpsk2n0j3
  - &pve-app-1
    age1vs8ffqtt3hfdtur82tv59z6kfwf27nk4e46nrkrj79jcmuxdsy2sag38sf
  - &pve-database
    age1m72xl459t3rws9y9m8ks2madx64f86dde33www6fqpnd6h4lec2skhlwxd
  - &pve-monitoring
    age1trh5rr42turkhzcxyxfv3ana72htqlevdglnsdyhn9e3atct7vpshyg87q
  - &pve-nix-builder
    age1zd58799unxaj4a47kkwxzd2a2jqwycz8hu9c0asg32lu5amx4ytq7mtjx0
  - &pve-proxy
    age16fd6tkmtpqy9kg04s0amn37mdj2vp0p7fngalu3244kw589x9qvqfnw62q

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *murderbot
          - *caretaker
          - *oci-proxy-server
          - *oci-auth-server
          - *oci-vpn-server
          - *pve-app-1
          - *pve-database
          - *pve-monitoring
          - *pve-nix-builder
          - *pve-proxy

  - path_regex: secrets/oci-auth-server\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *oci-auth-server

  - path_regex: secrets/oci-vpn-server\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *oci-vpn-server

  - path_regex: secrets/pve-app-1\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *pve-app-1

  - path_regex: secrets/pve-database\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *pve-database

  - path_regex: secrets/pve-monitoring\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *pve-monitoring

stores:
  yaml:
    indent: 2
  json:
    indent: 2
