keys:
  - &accesscontrolsystem
    age1rx9mw350ymp2xwua05peyg0f8s354ad8lxl9kkzwkg7pmwnh2q3qvg3z8e
  - &meshcontrol
    age1knvvq7pkyyf0c3qsn5thssg2wg3yzvaay9ewxyqzc3gd8xlctyas7jfz3r
  - &watchfulsystem
    age1xgqt4c8v3uv0yeq5mfdj32ecy7qgzm65gg3qgtqprr6vg5aedgxqzh20lc
  - &caretaker
    age1gqvw59226drpwn8942x55jcf5zca5gfupj9eppmeagfevx3pupzs78dfs6
  - &heartbeat
    age1r84yxudulk0jgdtgcmu0qx79ztuxzrzrk4jl5s9n52x4874q35cqzu4enh
  - &trialunit
    age1pcju0zkh2k3f8m7856k9ftzkjqw538jf255t2azusf9yr6v2nqksfn2pwa
  - &murderbot
    age1s90xwvtqw9at892s8tyde9lp8vu3rs2lde7pwh7hayuc2sahmv6qmkwpff

creation_rules:
  - path_regex: ^secrets/secrets\.sops\.yaml$
    key_groups:
      - age:
          - *accesscontrolsystem
          - *meshcontrol
          - *watchfulsystem
          - *caretaker
          - *heartbeat
          - *trialunit
          - *murderbot

  - path_regex: ^secrets/headscale-dns\.sops\.yaml$
    key_groups:
      - age:
        - *meshcontrol
        - *murderbot
        - *trialunit

  - path_regex: ^secrets/headscale-acl\.sops\.yaml$
    key_groups:
      - age:
        - *meshcontrol
        - *murderbot
        - *trialunit

  - path_regex: ^machines/accesscontrolsystem/secrets\.sops\.yaml$
    key_groups:
      - age:
        - *accesscontrolsystem
        - *murderbot


  - path_regex: ^machines/meshcontrol/secrets\.sops\.yaml$
    key_groups:
      - age:
        - *meshcontrol
        - *murderbot

  - path_regex: ^machines/watchfulsystem/secrets\.sops\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *watchfulsystem

  - path_regex: ^machines/caretaker/secrets\.sops\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *caretaker

  - path_regex: ^machines/heartbeat/secrets\.sops\.yaml$
    key_groups:
      - age:
        - *heartbeat
        - *murderbot

  - path_regex: ^machines/trialunit/secrets\.sops\.yaml$
    key_groups:
      - age:
        - *trialunit
        - *murderbot

stores:
  yaml:
    indent: 2
  json:
    indent: 2
