keys:
  - &accesscontrolsystem
    age1rx9mw350ymp2xwua05peyg0f8s354ad8lxl9kkzwkg7pmwnh2q3qvg3z8e
  - &meshcontrol
    age1knvvq7pkyyf0c3qsn5thssg2wg3yzvaay9ewxyqzc3gd8xlctyas7jfz3r
  - &watchfulsystem
    age1xgqt4c8v3uv0yeq5mfdj32ecy7qgzm65gg3qgtqprr6vg5aedgxqzh20lc
  - &heartbeat
    age1r84yxudulk0jgdtgcmu0qx79ztuxzrzrk4jl5s9n52x4874q35cqzu4enh
  - &murderbot
    age1s90xwvtqw9at892s8tyde9lp8vu3rs2lde7pwh7hayuc2sahmv6qmkwpff
  - &caretaker
    age1gqvw59226drpwn8942x55jcf5zca5gfupj9eppmeagfevx3pupzs78dfs6

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *accesscontrolsystem
          - *meshcontrol
          - *watchfulsystem
          - *heartbeat
          - *murderbot
          - *caretaker

  - path_regex: secrets/accesscontrolsystem-server\.yaml$
    key_groups:
      - age:
        - *accesscontrolsystem
        - *murderbot

  - path_regex: secrets/headscale-dns\.yaml$
    key_groups:
      - age:
        - *meshcontrol
        - *murderbot

  - path_regex: secrets/meshcontrol-server\.yaml$
    key_groups:
      - age:
        - *meshcontrol
        - *murderbot

  - path_regex: secrets/watchfulsystem-server\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *watchfulsystem

  - path_regex: secrets/heartbeat-server\.yaml$
    key_groups:
      - age:
        - *heartbeat
        - *murderbot

  - path_regex: secrets/caretaker\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *caretaker

stores:
  yaml:
    indent: 2
  json:
    indent: 2
