keys:
  - &murderbot age1s90xwvtqw9at892s8tyde9lp8vu3rs2lde7pwh7hayuc2sahmv6qmkwpff
  - &oci-auth-server age1357vpgg20nzv06key6scrw2ykyuw669m578tvzu7h0y8e8e2lsgqavux8g
  - &oci-vpn-server age13tez0lp6f7235nxlw9ddszfqsl0v748l5pu9nvt7yz3a9ewxky8qnntpjd
  - &pve-server-1 age1yt77nvav359rslqx62ppfp4rdzyde5ampkzjqml97cr5chzxlvxqtnenqp
  - &pve-server-monitoring
    age17v58lelflw6rs3s0mak9ewa8vqnykctjp6fkn2z9mfurs0lduu7szlh4qx
  - &pve-server-container
    age1qejwnmzypyvq0a6w250cha5pl5h385z8vx3ys4feckyu22wxuqgsjzf6mg

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *murderbot
          - *oci-auth-server
          - *oci-vpn-server
          - *pve-server-1
          - *pve-server-monitoring
          - *pve-server-container

  - path_regex: secrets/oci-restic\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *oci-auth-server
        - *oci-vpn-server

  - path_regex: secrets/hl-restic\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *pve-server-1
        - *pve-server-monitoring
        - *pve-server-container

  - path_regex: secrets/headscale\.yaml$
    key_groups:
      - age:
        - *murderbot
        - *oci-vpn-server

  - path_regex: ^secrets/authentik-env$
    key_groups:
      - age:
        - *murderbot
        - *oci-auth-server

  - path_regex: ^secrets/vaultwarden-env$
    key_groups:
      - age:
        - *murderbot
        - *pve-server-1

stores:
  yaml:
    indent: 2
  json:
    indent: 2
