{
  config,
  lib,
  pkgs,
  ...
}: let
  headscaleCfg = config.homelab.services.headscale;
in {
  config = lib.mkIf headscaleCfg.enable (
    let
      inherit (config.homelab.services.headscale) adminUser;

      aclConfig = {
        # Groups definition
        groups = {
          "group:admins" = [adminUser];
        };

        acls = [
          # Allow all connections within the tailnet
          {
            action = "accept";
            src = ["*"];
            dst = ["*:*"];
          }
          # Allow admin to connect to their own services
          {
            action = "accept";
            src = [adminUser];
            dst = ["${adminUser}:*"];
          }
        ];
      };

      # Convert to HuJSON format with comments
      aclHuJson = ''
        // Headscale ACL Policy - Generated by NixOS
        // Admin user: ${adminUser}

        ${builtins.toJSON aclConfig}
      '';

      aclFile = pkgs.writeText "acl-policy.hujson" aclHuJson;
    in {
      services = {
        headscale = {
          settings = {
            policy.path = aclFile;
          };
        };
      };
    }
  );
}
