{
  config,
  lib,
  pkgs,
  ...
}: let
  domain = "mantannest.com";
  headscaleDomain = "headscale.${domain}";
  authDomain = "auth.${domain}";
in {
  options.services.headscale = {
    adminUser = lib.mkOption {
      type = lib.types.str;
      default = "admin";
      description = "Username for the headscale admin user";
    };
  };

  config = let
    inherit (config.services.headscale) adminUser;

    aclConfig = {
      # Groups definition
      groups = {
        "group:admins" = [adminUser];
      };

      acls = [
        # Allow all connections within the tailnet
        {
          action = "accept";
          src = ["*"];
          dst = ["*:*"];
        }
        # Allow admin to connect to their own services
        {
          action = "accept";
          src = [adminUser];
          dst = ["${adminUser}:*"];
        }
      ];

      # Auto-approvers section for routes
      autoApprovers = {
        routes = {
          "0.0.0.0/0" = [adminUser];
          "10.0.0.0/16" = [adminUser];
          "172.16.0.0/24" = [adminUser];
        };

        exitNode = [adminUser];
      };
    };

    # Convert to HuJSON format with comments
    aclHuJson = ''
      // Headscale ACL Policy - Generated by NixOS
      // Admin user: ${adminUser}

      ${builtins.toJSON aclConfig}
    '';

    aclFile = pkgs.writeText "acl-policy.hujson" aclHuJson;
  in {
    sops.secrets = {
      "headscale-authentik-client-secret" = {
        owner = "headscale";
        sopsFile = ./../../../secrets/oci-vpn-server.yaml;
      };
    };

    services = {
      headscale = {
        enable = true;
        adminUser = "admin";
        port = 3009;
        settings = {
          dns = {
            base_domain = "dns.headscale.mantannest.com";

            extra_records = [
              {
                name = "grafana.mantannest.com";
                type = "A";
                value = "100.64.0.7";
              }
              {
                name = "photos.mantannest.com";
                type = "A";
                value = "100.64.0.3";
              }
              {
                name = "passwords.mantannest.com";
                type = "A";
                value = "100.64.0.3";
              }
              {
                name = "loki.monitoring.server.mantannest.com";
                type = "A";
                value = "100.64.0.7";
              }
            ];
          };

          logtail.enabled = false;

          oidc = {
            only_start_if_oidc_is_available = true;
            issuer = "https://${authDomain}/application/o/headscale/";
            client_id = "Pjad107mj4JsZRnmbTMzbGiNqIolCMFn2jF3dBeA";
            client_secret_path = config.sops.secrets."headscale-authentik-client-secret".path;

            scope = [
              "openid"
              "profile"
              "email"
              "custom"
            ];

            pkce = {
              enabled = true;
              method = "S256";
            };

            strip_email_domain = true;
          };

          policy.path = aclFile;
          server_url = "https://${headscaleDomain}";
        };
      };
    };

    environment.persistence."/nix/persist" = {
      directories = [
        "/var/lib/headscale/"
      ];
    };
  };
}
