# Backup sub-module — restic repository configuration and systemd service.
{
  config,
  lib,
  ...
}: let
  homelabCfg = config.homelab;

  resticEnabled = homelabCfg.services.restic.enable;

  zfsDatasets = homelabCfg.zfs.datasets;
  resticDatasetEntries =
    lib.filterAttrs (_: ds: ds.restic.enable) zfsDatasets;

  datasetNames = lib.attrNames resticDatasetEntries;
  inherit (homelabCfg.services.backup) extraPaths;

  backupRoot = toString homelabCfg.services.backup.backupRoot;
  mountPathFor = name: "${backupRoot}/${name}";
  resticPaths = map mountPathFor datasetNames;

  hasResticPaths = (datasetNames != []) || (extraPaths != []);

  checkCfg = homelabCfg.services.restic.check;
in {
  config = lib.mkIf resticEnabled {
    # Repository integrity check, on its own weekly timer.
    #
    # This used to run inline at the end of every nightly backup, which was
    # wrong twice over. It downloads --read-data-subset of the repo from S3 on
    # every host every night (3m31s on heartbeat), and a nightly 5% sample
    # re-checks the same small slice far more often than a weekly larger one
    # while covering less of the repo over any given month.
    #
    # It is also a real unit now rather than a shell line, so a failure marks
    # the unit failed instead of being swallowed into `|| echo`.
    systemd = lib.mkIf (checkCfg.enable && hasResticPaths) {
      services = {
        backup-restic-check = {
          description = "Verify restic repository integrity";
          after = ["network-online.target"];
          wants = ["network-online.target"];
          restartIfChanged = false;

          serviceConfig = {
            Type = "oneshot";
            # The restic-backup wrapper is generated by the upstream NixOS
            # module with the repo and credentials already wired in.
            ExecStart = "/run/current-system/sw/bin/restic-backup check --read-data-subset=${checkCfg.readDataSubset}";
            TimeoutStartSec = "6h";
          };
        };
      };

      timers = {
        backup-restic-check = {
          wantedBy = ["timers.target"];
          timerConfig = {
            OnCalendar = checkCfg.onCalendar;
            Persistent = true;
          };
        };
      };
    };

    services = {
      restic = {
        backups = {
          backup = lib.mkIf hasResticPaths {
            inherit (homelabCfg.services.restic) pruneOpts;

            initialize = true;

            environmentFile = config.sops.secrets."restic/.env".path;
            repositoryFile = config.sops.secrets."restic/repo".path;
            passwordFile = config.sops.secrets."restic/password".path;

            extraOptions = [
              "s3.connections=10"
              "--no-extra-verify"
            ];

            # Restic backs up *already-mounted* snapshot views
            paths = resticPaths ++ extraPaths;

            timerConfig = null;
          };
        };
      };
    };
  };
}
